# Generated by Django 6.0 on 2025-12-30 03:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GigPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('teacher_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('khalti_pidx', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('khalti_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('gig', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='gigs.gig')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gig_payments', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['parent', 'status'], name='payments_gi_parent__d1d86b_idx'), models.Index(fields=['teacher', 'status'], name='payments_gi_teacher_b31787_idx'), models.Index(fields=['khalti_pidx'], name='payments_gi_khalti__e7e84b_idx')],
            },
        ),
    ]
