# Generated by Django 6.0 on 2025-12-30 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_gigpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gigpayment',
            name='teacher_amount',
        ),
    ]
