# Generated by Django 6.0 on 2025-12-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_verificationdocument_verified_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationdocument',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='verificationdocument',
            name='verified',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
