# Generated by Django 6.0 on 2025-12-26 14:49

import django.db.models.deletion
import profiles.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_verificationdocument_rejection_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentVerificationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=500, upload_to=profiles.models.get_parent_document_upload_path)),
                ('document_type', models.CharField(choices=[('citizenship', 'Citizenship/ID'), ('id_card', 'ID Card'), ('other', 'Other')], max_length=20)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(blank=True, default=None, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.RemoveField(
            model_name='parentdocument',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='verificationdocument',
            name='file_url',
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='verificationdocument',
            name='file',
            field=models.FileField(max_length=500, null=True, upload_to=profiles.models.get_teacher_document_upload_path),
        ),
        migrations.AlterField(
            model_name='verificationdocument',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_teacher_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='verificationdocument',
            index=models.Index(fields=['teacher', '-uploaded_at'], name='profiles_ve_teacher_dd1999_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationdocument',
            index=models.Index(fields=['verified'], name='profiles_ve_verifie_cdf972_idx'),
        ),
        migrations.AddField(
            model_name='parentverificationdocument',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='profiles.parentprofile'),
        ),
        migrations.AddField(
            model_name='parentverificationdocument',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_parent_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ParentDocument',
        ),
        migrations.AddIndex(
            model_name='parentverificationdocument',
            index=models.Index(fields=['parent', '-uploaded_at'], name='profiles_pa_parent__8ff7bf_idx'),
        ),
        migrations.AddIndex(
            model_name='parentverificationdocument',
            index=models.Index(fields=['verified'], name='profiles_pa_verifie_6841d2_idx'),
        ),
    ]
