# Generated by Django 6.0 on 2026-05-04 06:37

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_update_parent_document_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentprofile',
            name='kyc_photo',
            field=models.ImageField(blank=True, help_text='Photo with clear visibility of face, eyes, and ears for KYC verification', max_length=500, null=True, upload_to=profiles.models.get_parent_kyc_photo_upload_path),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='kyc_photo_rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for KYC photo rejection'),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='kyc_photo_verified',
            field=models.BooleanField(default=False, help_text='Whether the KYC photo has been verified by admin'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='kyc_photo',
            field=models.ImageField(blank=True, help_text='Photo with clear visibility of face, eyes, and ears for KYC verification', max_length=500, null=True, upload_to=profiles.models.get_kyc_photo_upload_path),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='kyc_photo_rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for KYC photo rejection'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='kyc_photo_verified',
            field=models.BooleanField(default=False, help_text='Whether the KYC photo has been verified by admin'),
        ),
    ]
