# Generated by Codex on 2026-05-04

from django.db import migrations, models


def split_existing_teacher_citizenship_documents(apps, schema_editor):
    VerificationDocument = apps.get_model("profiles", "VerificationDocument")
    VerificationDocument.objects.filter(document_type="citizenship").update(
        document_type="citizenship_front"
    )


def restore_old_teacher_citizenship_documents(apps, schema_editor):
    VerificationDocument = apps.get_model("profiles", "VerificationDocument")
    VerificationDocument.objects.filter(
        document_type__in=["citizenship_front", "citizenship_back"]
    ).update(document_type="citizenship")


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0008_parentprofile_kyc_photo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verificationdocument",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("citizenship_front", "Citizenship Front"),
                    ("citizenship_back", "Citizenship Back"),
                    ("academic", "Academic Certificate"),
                    ("experience", "Experience Letter"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.RunPython(
            split_existing_teacher_citizenship_documents,
            restore_old_teacher_citizenship_documents,
        ),
    ]
