# Generated by Django 6.0 on 2026-05-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_profile_citizenship_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationdocument',
            name='document_type',
            field=models.CharField(choices=[('citizenship_front', 'Citizenship Front'), ('citizenship_back', 'Citizenship Back'), ('academic', 'Academic Certificate'), ('cv', 'CV'), ('other', 'Other')], max_length=20),
        ),
    ]
