# Generated by Django 6.0 on 2026-04-29 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_is_email_verified'),
        ('accounts', '0002_user_profile_picture'),
    ]

    operations = [
    ]
