# Generated by Codex on 2026-04-30

from django.db import migrations, models


def mark_existing_active_users_verified(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.filter(is_active=True).update(is_email_verified=True)
    User.objects.filter(is_superuser=True).update(
        is_active=True,
        is_email_verified=True,
    )


def mark_everyone_verified_before_remove(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.update(is_email_verified=True)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_merge_20260429_1247"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            mark_existing_active_users_verified,
            mark_everyone_verified_before_remove,
        ),
    ]
