# Generated by Codex on 2026-05-04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_is_email_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_picture_rejection_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_picture_verified",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_picture_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_picture_verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_profile_pictures",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
