# Generated by Django 6.0 on 2026-05-13 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userreport',
            new_name='reports_use_status_78241a_idx',
            old_name='reports_use_status_371ac9_idx',
        ),
        migrations.RenameIndex(
            model_name='userreport',
            new_name='reports_use_categor_ba6b3e_idx',
            old_name='reports_use_categor_126e50_idx',
        ),
        migrations.RenameIndex(
            model_name='userreport',
            new_name='reports_use_reporte_2ae136_idx',
            old_name='reports_use_reporte_320957_idx',
        ),
    ]
