# Generated by Django 6.0 on 2025-12-25 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('application_received', 'Application Received'), ('teacher_selected', 'Teacher Selected'), ('selection_accepted', 'Selection Accepted'), ('selection_rejected', 'Selection Rejected'), ('payment_initiated', 'Payment Initiated'), ('escrow_funded', 'Escrow Funded'), ('gig_started', 'Gig Started'), ('completion_requested', 'Completion Requested'), ('payment_released', 'Payment Released'), ('gig_cancelled', 'Gig Cancelled'), ('dispute_opened', 'Dispute Opened')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_f2ad08_idx')],
            },
        ),
    ]
