# Generated by Django 6.0 on 2025-12-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('application_received', 'Application Received'), ('teacher_selected', 'Teacher Selected'), ('selection_accepted', 'Selection Accepted'), ('selection_rejected', 'Selection Rejected'), ('payment_initiated', 'Payment Initiated'), ('escrow_funded', 'Escrow Funded'), ('payment_released', 'Payment Released'), ('payment_refunded', 'Payment Refunded'), ('gig_started', 'Gig Started'), ('gig_completed', 'Gig Completed'), ('gig_cancelled', 'Gig Cancelled'), ('completion_requested', 'Completion Requested'), ('dispute_opened', 'Dispute Opened'), ('dispute_resolved', 'Dispute Resolved'), ('premium_activated', 'Premium Activated'), ('premium_expiring', 'Premium Expiring Soon'), ('premium_expired', 'Premium Expired'), ('document_verified', 'Document Verified'), ('document_rejected', 'Document Rejected'), ('document_uploaded', 'Document Uploaded'), ('system_announcement', 'System Announcement'), ('test', 'Test Notification')], max_length=30),
        ),
    ]
